# Dependabot takes the effort out of maintaining your dependencies.
# You can use it to ensure that your repository automatically keeps
# up with the latest releases of the packages and applications it
# depends on.
#
# When Dependabot identifies an outdated dependency, it raises a
# pull request to update the manifest to the latest version of
# the dependency.
#
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '12:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
    commit-message:
      prefix: '[dependabot]'
